In [1]:
# Importing all the necessary libraries for data processing and plotting

import pandas as pd
import numpy as np
import openpyxl

import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import pycountry as pyc

# Warnings
import warnings
warnings.filterwarnings('ignore')

# Optional: display settings
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)
pd.set_option('display.float_format', '{:.2f}'.format)

In [2]:
# Loading the total dataset.

dataf= pd.read_excel(r"C:\Users\dell\Desktop\CO2-dataset.xlsx")
print(dataf.head())

  Country Name Country Code      Indicator Name  Indicator Code    1960  \
0        Aruba          ABW  CO2 emissions (kt)  EN.ATM.CO2E.KT     NaN
1      Andorra          AND  CO2 emissions (kt)  EN.ATM.CO2E.KT     NaN
2  Afghanistan          AFG  CO2 emissions (kt)  EN.ATM.CO2E.KT  414.37
3       Angola          AGO  CO2 emissions (kt)  EN.ATM.CO2E.KT  550.05
4      Albania          ALB  CO2 emissions (kt)  EN.ATM.CO2E.KT 2024.18

     1961    1962    1963    1964    1965    1966    1967    1968    1969  \
0     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
1     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2  491.38  689.40  707.73  839.74 1008.42 1092.77 1283.45 1224.78  942.42
3  454.71 1180.77 1151.44 1224.78 1188.11 1554.81  993.76 1672.15 2786.92
4 2280.87 2464.22 2082.86 2016.85 2174.53 2552.23 2680.58 3072.95 3245.30

     1970    1971    1972    1973    1974    1975    1976    1977    1978  \
0     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
1     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2 1672.15 1895.84 1532.81 1639.15 1917.84 2126.86 1987.51 2390.88 2159.86
3 3582.66 3410.31 4506.74 4880.78 4873.44 4415.07 3285.63 3534.99 5412.49
4 3744.01 4352.73 5643.51 5291.48 4345.40 4594.75 4950.45 5720.52 6494.26

     1979    1980    1981    1982    1983    1984    1985    1986    1987  \
0     NaN     NaN     NaN     NaN     NaN     NaN     NaN  179.68  447.37
1     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2 2240.54 1760.16 1983.85 2101.19 2522.90 2830.92 3509.32 3142.62 3124.28
3 5504.17 5346.49 5280.48 4649.76 5115.47 5009.12 4701.09 4660.76 5815.86
4 7587.02 5170.47 7341.33 7308.33 7631.03 7825.38 7880.38 8056.40 7444.01

     1988    1989    1990    1991    1992    1993    1994     1995     1996  \
0  612.39  649.06 1840.83 1928.84 1723.49 1771.16 1763.83  1782.16  1800.50
1     NaN     NaN     NaN     NaN     NaN     NaN     NaN   407.04   425.37
2 2867.59 2775.92 2676.91 2493.56 1426.46 1375.12 1320.12  1268.78  1199.11
3 5130.13 5009.12 4429.74 4367.40 4418.73 5801.19 3890.69 11012.00 10491.29
4 7326.67 8984.15 7488.01 3971.36 2387.22 2343.21 1928.84  2086.52  2016.85

     1997    1998    1999    2000    2001     2002    2003     2004     2005  \
0 1837.17 1712.49 1749.16 2321.21 2357.88  2372.55 2416.55  2420.22  2497.23
1  458.38  484.04  513.38  524.38  524.38   531.72  535.38   564.72   575.72
2 1114.77 1056.10  832.41  781.07  645.39   894.75 1037.76   957.09  1338.45
3 7381.67 7308.33 9156.50 9541.53 9732.22 12665.82 9064.82 18793.38 19156.41
4 1543.81 1752.83 2984.94 3021.61 3223.29  3751.34 4294.06  4165.71  4253.72

      2006     2007     2008     2009     2010     2011
0  2497.23  2592.57  2508.23  2522.90  2456.89  2438.55
1   546.38   539.05   539.05   517.05   517.05   491.38
2  1657.48  2280.87  4217.05  6776.62  8470.77 12251.45
3 22266.02 25151.95 27172.47 29361.67 29743.04 29710.03
4  3865.02  4477.41  4657.09  4488.41  4415.07  4668.09

In [3]:
# Displaying the structure and basic info about data.

print(dataf.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 248 entries, 0 to 247
Data columns (total 56 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    248 non-null    object
 1   Country Code    248 non-null    object
 2   Indicator Name  248 non-null    object
 3   Indicator Code  248 non-null    object
 4   1960            178 non-null    float64
 5   1961            179 non-null    float64
 6   1962            180 non-null    float64
 7   1963            181 non-null    float64
 8   1964            186 non-null    float64
 9   1965            186 non-null    float64
 10  1966            186 non-null    float64
 11  1967            186 non-null    float64
 12  1968            185 non-null    float64
 13  1969            186 non-null    float64
 14  1970            188 non-null    float64
 15  1971            189 non-null    float64
 16  1972            192 non-null    float64
 17  1973            192 non-null    float64
 18  1974            192 non-null    float64
 19  1975            192 non-null    float64
 20  1976            192 non-null    float64
 21  1977            192 non-null    float64
 22  1978            192 non-null    float64
 23  1979            192 non-null    float64
 24  1980            192 non-null    float64
 25  1981            192 non-null    float64
 26  1982            192 non-null    float64
 27  1983            192 non-null    float64
 28  1984            192 non-null    float64
 29  1985            192 non-null    float64
 30  1986            193 non-null    float64
 31  1987            193 non-null    float64
 32  1988            193 non-null    float64
 33  1989            193 non-null    float64
 34  1990            195 non-null    float64
 35  1991            196 non-null    float64
 36  1992            220 non-null    float64
 37  1993            220 non-null    float64
 38  1994            221 non-null    float64
 39  1995            223 non-null    float64
 40  1996            222 non-null    float64
 41  1997            224 non-null    float64
 42  1998            226 non-null    float64
 43  1999            226 non-null    float64
 44  2000            227 non-null    float64
 45  2001            227 non-null    float64
 46  2002            228 non-null    float64
 47  2003            228 non-null    float64
 48  2004            228 non-null    float64
 49  2005            230 non-null    float64
 50  2006            231 non-null    float64
 51  2007            232 non-null    float64
 52  2008            232 non-null    float64
 53  2009            232 non-null    float64
 54  2010            232 non-null    float64
 55  2011            232 non-null    float64
dtypes: float64(52), object(4)
memory usage: 108.6+ KB
None

In [4]:
# Checking for the null values in the data.

print(dataf.isnull().sum())

Country Name       0
Country Code       0
Indicator Name     0
Indicator Code     0
1960              70
1961              69
1962              68
1963              67
1964              62
1965              62
1966              62
1967              62
1968              63
1969              62
1970              60
1971              59
1972              56
1973              56
1974              56
1975              56
1976              56
1977              56
1978              56
1979              56
1980              56
1981              56
1982              56
1983              56
1984              56
1985              56
1986              55
1987              55
1988              55
1989              55
1990              53
1991              52
1992              28
1993              28
1994              27
1995              25
1996              26
1997              24
1998              22
1999              22
2000              21
2001              21
2002              20
2003              20
2004              20
2005              18
2006              17
2007              16
2008              16
2009              16
2010              16
2011              16
dtype: int64

In [5]:
# Dropping null values and then confirming it.

df= dataf.dropna()
df.info()
print(df.isnull().sum().sum())

<class 'pandas.core.frame.DataFrame'>
Index: 175 entries, 2 to 245
Data columns (total 56 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    175 non-null    object
 1   Country Code    175 non-null    object
 2   Indicator Name  175 non-null    object
 3   Indicator Code  175 non-null    object
 4   1960            175 non-null    float64
 5   1961            175 non-null    float64
 6   1962            175 non-null    float64
 7   1963            175 non-null    float64
 8   1964            175 non-null    float64
 9   1965            175 non-null    float64
 10  1966            175 non-null    float64
 11  1967            175 non-null    float64
 12  1968            175 non-null    float64
 13  1969            175 non-null    float64
 14  1970            175 non-null    float64
 15  1971            175 non-null    float64
 16  1972            175 non-null    float64
 17  1973            175 non-null    float64
 18  1974            175 non-null    float64
 19  1975            175 non-null    float64
 20  1976            175 non-null    float64
 21  1977            175 non-null    float64
 22  1978            175 non-null    float64
 23  1979            175 non-null    float64
 24  1980            175 non-null    float64
 25  1981            175 non-null    float64
 26  1982            175 non-null    float64
 27  1983            175 non-null    float64
 28  1984            175 non-null    float64
 29  1985            175 non-null    float64
 30  1986            175 non-null    float64
 31  1987            175 non-null    float64
 32  1988            175 non-null    float64
 33  1989            175 non-null    float64
 34  1990            175 non-null    float64
 35  1991            175 non-null    float64
 36  1992            175 non-null    float64
 37  1993            175 non-null    float64
 38  1994            175 non-null    float64
 39  1995            175 non-null    float64
 40  1996            175 non-null    float64
 41  1997            175 non-null    float64
 42  1998            175 non-null    float64
 43  1999            175 non-null    float64
 44  2000            175 non-null    float64
 45  2001            175 non-null    float64
 46  2002            175 non-null    float64
 47  2003            175 non-null    float64
 48  2004            175 non-null    float64
 49  2005            175 non-null    float64
 50  2006            175 non-null    float64
 51  2007            175 non-null    float64
 52  2008            175 non-null    float64
 53  2009            175 non-null    float64
 54  2010            175 non-null    float64
 55  2011            175 non-null    float64
dtypes: float64(52), object(4)
memory usage: 77.9+ KB
0

In [6]:
# Keeping the copy of the raw data and Selecting the necessary columns from the data set.

rawdf= dataf[['Country Name', 'Country Code', '2000', '2011']]
df= rawdf.copy()
df

         Country Name Country Code      2000      2011
0               Aruba          ABW   2321.21   2438.55
1             Andorra          AND    524.38    491.38
2         Afghanistan          AFG    781.07  12251.45
3              Angola          AGO   9541.53  29710.03
4             Albania          ALB   3021.61   4668.09
..                ...          ...       ...       ...
243       Yemen, Rep.          YEM  14638.66  22295.36
244      South Africa          ZAF 368610.51 477241.72
245  Congo, Dem. Rep.          COD   1646.48   3424.98
246            Zambia          ZMB   1822.50   3047.28
247          Zimbabwe          ZWE  13886.93   9860.56

[248 rows x 4 columns]

In [7]:
# Filtering out unncecssary rows from the data. (Selecting COUNTRIES only.)
import pycountry as pyc

valid_codes = {c.alpha_3 for c in pyc.countries}
df= df[df['Country Code'].isin(valid_codes)]
df

         Country Name Country Code      2000      2011
0               Aruba          ABW   2321.21   2438.55
1             Andorra          AND    524.38    491.38
2         Afghanistan          AFG    781.07  12251.45
3              Angola          AGO   9541.53  29710.03
4             Albania          ALB   3021.61   4668.09
..                ...          ...       ...       ...
243       Yemen, Rep.          YEM  14638.66  22295.36
244      South Africa          ZAF 368610.51 477241.72
245  Congo, Dem. Rep.          COD   1646.48   3424.98
246            Zambia          ZMB   1822.50   3047.28
247          Zimbabwe          ZWE  13886.93   9860.56

[212 rows x 4 columns]

In [8]:
# Converting units from kilotones to megatones for better readability.

df= df[['Country Name', '2000', '2011']]
df['Country']= df['Country Name']
df['2000_Mt']= df['2000']/1000
df['2011_Mt']= df['2011']/1000

df= df[['Country', '2000_Mt', '2011_Mt']]
df
#

              Country  2000_Mt  2011_Mt
0               Aruba     2.32     2.44
1             Andorra     0.52     0.49
2         Afghanistan     0.78    12.25
3              Angola     9.54    29.71
4             Albania     3.02     4.67
..                ...      ...      ...
243       Yemen, Rep.    14.64    22.30
244      South Africa   368.61   477.24
245  Congo, Dem. Rep.     1.65     3.42
246            Zambia     1.82     3.05
247          Zimbabwe    13.89     9.86

[212 rows x 3 columns]

In [9]:
# Dropping rows with null values and reseting the indexes of the data,
# in order to avoid further confusion in the calculation process.

df.isnull().sum()
df= df.dropna()

df.reset_index(drop= True, inplace= True)
df

              Country  2000_Mt  2011_Mt
0               Aruba     2.32     2.44
1             Andorra     0.52     0.49
2         Afghanistan     0.78    12.25
3              Angola     9.54    29.71
4             Albania     3.02     4.67
..                ...      ...      ...
189       Yemen, Rep.    14.64    22.30
190      South Africa   368.61   477.24
191  Congo, Dem. Rep.     1.65     3.42
192            Zambia     1.82     3.05
193          Zimbabwe    13.89     9.86

[194 rows x 3 columns]

In [10]:
import numpy as np

# 1. Permanently KEEP only rows where '2000_Mt' is greater than 40

df = df[df['2000_Mt'] > 40]
df

                       Country  2000_Mt  2011_Mt
5         United Arab Emirates   112.56   178.48
6                    Argentina   141.08   190.03
9                    Australia   329.48   369.04
10                     Austria    62.19    65.20
13                     Belgium   114.89    97.77
17                    Bulgaria    43.53    49.34
21                     Belarus    53.47    63.30
25                      Brazil   327.98   439.41
31                      Canada   534.48   485.46
33                       Chile    58.82    79.41
34                       China  3405.18  9019.52
38                    Colombia    57.92    72.42
45              Czech Republic   123.68   109.49
46                     Germany   829.98   729.46
49                     Denmark    51.33    40.38
51                     Algeria    87.93   121.76
53            Egypt, Arab Rep.   141.33   220.79
55                       Spain   294.43   270.68
58                     Finland    52.43    54.77
60                      France   364.06   338.81
64              United Kingdom   541.80   448.24
71                      Greece    91.62    84.05
76        Hong Kong SAR, China    40.47    40.27
80                     Hungary    55.81    48.49
81                   Indonesia   263.42   563.98
82                       India  1186.66  2074.34
83                     Ireland    41.24    36.07
84          Iran, Islamic Rep.   372.70   586.60
85                        Iraq    72.45   133.65
87                      Israel    60.26    69.52
88                       Italy   450.56   397.99
91                       Japan  1219.45  1187.66
92                  Kazakhstan   127.77   261.76
98                 Korea, Rep.   447.56   589.43
99                      Kuwait    53.56    91.03
103                      Libya    47.11    39.02
114                     Mexico   382.51   466.55
125                   Malaysia   126.60   225.69
129                    Nigeria    79.18    88.03
131                Netherlands   165.36   168.01
136                   Pakistan   106.45   163.45
139                Philippines    73.31    82.01
142                     Poland   299.28   317.29
143  Korea, Dem. People’s Rep.    76.70    73.58
144                   Portugal    62.97    49.72
148                    Romania    89.98    84.83
149         Russian Federation  1558.11  1808.07
151               Saudi Arabia   296.94   520.28
154                  Singapore    49.01    22.39
163                     Sweden    49.35    52.14
166       Syrian Arab Republic    51.05    57.67
170                   Thailand   188.36   303.37
176                     Turkey   216.15   320.84
179                    Ukraine   320.77   286.23
181              United States  5701.83  5305.57
182                 Uzbekistan   121.06   114.86
184              Venezuela, RB   152.42   188.82
185                    Vietnam    53.64   173.21
190               South Africa   368.61   477.24

In [11]:
# Calculating percentage growth and looking for the fastest growing emitters (2000-2011).
df['Growth %']= ((df['2011_Mt']- df['2000_Mt'])/df['2000_Mt'])*100

df= df.sort_values(by= 'Growth %', ascending= False).head(15)
df= df.reset_index(drop= True)
df.index= df.index+1
df

                 Country  2000_Mt  2011_Mt  Growth %
1                Vietnam    53.64   173.21    222.89
2                  China  3405.18  9019.52    164.88
3              Indonesia   263.42   563.98    114.10
4             Kazakhstan   127.77   261.76    104.87
5                   Iraq    72.45   133.65     84.49
6               Malaysia   126.60   225.69     78.27
7           Saudi Arabia   296.94   520.28     75.22
8                  India  1186.66  2074.34     74.80
9                 Kuwait    53.56    91.03     69.96
10              Thailand   188.36   303.37     61.06
11  United Arab Emirates   112.56   178.48     58.56
12    Iran, Islamic Rep.   372.70   586.60     57.39
13      Egypt, Arab Rep.   141.33   220.79     56.23
14              Pakistan   106.45   163.45     53.55
15                Turkey   216.15   320.84     48.43