In [279]:
# Importing all the necessary libraries for data processing and plotting

# !{sys.executable} -m pip install jinja2

import sys
import pandas as pd
import numpy as np
import openpyxl

import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import pycountry as pyc

# Warnings
import warnings
warnings.filterwarnings('ignore')

# Optional: display settings
pd.set_option('display.max_columns', 8)
pd.set_option('display.max_rows', 20)
pd.set_option('display.float_format', '{:.2f}'.format)

In [280]:
# Loading the total dataset.

dataf= pd.read_excel(r"C:\Users\dell\Desktop\CO2-dataset.xlsx")
print(dataf.head())

  Country Name Country Code      Indicator Name  Indicator Code  ...     2008  \
0        Aruba          ABW  CO2 emissions (kt)  EN.ATM.CO2E.KT  ...  2508.23
1      Andorra          AND  CO2 emissions (kt)  EN.ATM.CO2E.KT  ...   539.05
2  Afghanistan          AFG  CO2 emissions (kt)  EN.ATM.CO2E.KT  ...  4217.05
3       Angola          AGO  CO2 emissions (kt)  EN.ATM.CO2E.KT  ... 27172.47
4      Albania          ALB  CO2 emissions (kt)  EN.ATM.CO2E.KT  ...  4657.09

      2009     2010     2011
0  2522.90  2456.89  2438.55
1   517.05   517.05   491.38
2  6776.62  8470.77 12251.45
3 29361.67 29743.04 29710.03
4  4488.41  4415.07  4668.09

[5 rows x 56 columns]

In [281]:
# Displaying the structure and basic info about data.

print(dataf.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 248 entries, 0 to 247
Data columns (total 56 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    248 non-null    object
 1   Country Code    248 non-null    object
 2   Indicator Name  248 non-null    object
 3   Indicator Code  248 non-null    object
 4   1960            178 non-null    float64
 5   1961            179 non-null    float64
 6   1962            180 non-null    float64
 7   1963            181 non-null    float64
 8   1964            186 non-null    float64
 9   1965            186 non-null    float64
 10  1966            186 non-null    float64
 11  1967            186 non-null    float64
 12  1968            185 non-null    float64
 13  1969            186 non-null    float64
 14  1970            188 non-null    float64
 15  1971            189 non-null    float64
 16  1972            192 non-null    float64
 17  1973            192 non-null    float64
 18  1974            192 non-null    float64
 19  1975            192 non-null    float64
 20  1976            192 non-null    float64
 21  1977            192 non-null    float64
 22  1978            192 non-null    float64
 23  1979            192 non-null    float64
 24  1980            192 non-null    float64
 25  1981            192 non-null    float64
 26  1982            192 non-null    float64
 27  1983            192 non-null    float64
 28  1984            192 non-null    float64
 29  1985            192 non-null    float64
 30  1986            193 non-null    float64
 31  1987            193 non-null    float64
 32  1988            193 non-null    float64
 33  1989            193 non-null    float64
 34  1990            195 non-null    float64
 35  1991            196 non-null    float64
 36  1992            220 non-null    float64
 37  1993            220 non-null    float64
 38  1994            221 non-null    float64
 39  1995            223 non-null    float64
 40  1996            222 non-null    float64
 41  1997            224 non-null    float64
 42  1998            226 non-null    float64
 43  1999            226 non-null    float64
 44  2000            227 non-null    float64
 45  2001            227 non-null    float64
 46  2002            228 non-null    float64
 47  2003            228 non-null    float64
 48  2004            228 non-null    float64
 49  2005            230 non-null    float64
 50  2006            231 non-null    float64
 51  2007            232 non-null    float64
 52  2008            232 non-null    float64
 53  2009            232 non-null    float64
 54  2010            232 non-null    float64
 55  2011            232 non-null    float64
dtypes: float64(52), object(4)
memory usage: 108.6+ KB
None

In [282]:
# Checking for the null values in the data.

print(dataf.isnull().sum())

Country Name       0
Country Code       0
Indicator Name     0
Indicator Code     0
1960              70
                  ..
2007              16
2008              16
2009              16
2010              16
2011              16
Length: 56, dtype: int64

In [283]:
# Dropping null values and then confirming it.
df= dataf.dropna()
df.info()

print(df.isnull().sum().sum())

<class 'pandas.core.frame.DataFrame'>
Index: 175 entries, 2 to 245
Data columns (total 56 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    175 non-null    object
 1   Country Code    175 non-null    object
 2   Indicator Name  175 non-null    object
 3   Indicator Code  175 non-null    object
 4   1960            175 non-null    float64
 5   1961            175 non-null    float64
 6   1962            175 non-null    float64
 7   1963            175 non-null    float64
 8   1964            175 non-null    float64
 9   1965            175 non-null    float64
 10  1966            175 non-null    float64
 11  1967            175 non-null    float64
 12  1968            175 non-null    float64
 13  1969            175 non-null    float64
 14  1970            175 non-null    float64
 15  1971            175 non-null    float64
 16  1972            175 non-null    float64
 17  1973            175 non-null    float64
 18  1974            175 non-null    float64
 19  1975            175 non-null    float64
 20  1976            175 non-null    float64
 21  1977            175 non-null    float64
 22  1978            175 non-null    float64
 23  1979            175 non-null    float64
 24  1980            175 non-null    float64
 25  1981            175 non-null    float64
 26  1982            175 non-null    float64
 27  1983            175 non-null    float64
 28  1984            175 non-null    float64
 29  1985            175 non-null    float64
 30  1986            175 non-null    float64
 31  1987            175 non-null    float64
 32  1988            175 non-null    float64
 33  1989            175 non-null    float64
 34  1990            175 non-null    float64
 35  1991            175 non-null    float64
 36  1992            175 non-null    float64
 37  1993            175 non-null    float64
 38  1994            175 non-null    float64
 39  1995            175 non-null    float64
 40  1996            175 non-null    float64
 41  1997            175 non-null    float64
 42  1998            175 non-null    float64
 43  1999            175 non-null    float64
 44  2000            175 non-null    float64
 45  2001            175 non-null    float64
 46  2002            175 non-null    float64
 47  2003            175 non-null    float64
 48  2004            175 non-null    float64
 49  2005            175 non-null    float64
 50  2006            175 non-null    float64
 51  2007            175 non-null    float64
 52  2008            175 non-null    float64
 53  2009            175 non-null    float64
 54  2010            175 non-null    float64
 55  2011            175 non-null    float64
dtypes: float64(52), object(4)
memory usage: 77.9+ KB
0

In [284]:
# Keeping the copy of the raw data and Selecting the necessary columns from the data set.

rawdf= dataf[['Country Name', 'Country Code', '2000', '2011']]
df= rawdf.copy()
df

         Country Name Country Code      2000      2011
0               Aruba          ABW   2321.21   2438.55
1             Andorra          AND    524.38    491.38
2         Afghanistan          AFG    781.07  12251.45
3              Angola          AGO   9541.53  29710.03
4             Albania          ALB   3021.61   4668.09
..                ...          ...       ...       ...
243       Yemen, Rep.          YEM  14638.66  22295.36
244      South Africa          ZAF 368610.51 477241.72
245  Congo, Dem. Rep.          COD   1646.48   3424.98
246            Zambia          ZMB   1822.50   3047.28
247          Zimbabwe          ZWE  13886.93   9860.56

[248 rows x 4 columns]

In [285]:
# Filtering out unncecssary rows from the data. (Selecting COUNTRIES only.)
import pycountry as pyc

valid_codes = {c.alpha_3 for c in pyc.countries}
df= df[df['Country Code'].isin(valid_codes)]
df

         Country Name Country Code      2000      2011
0               Aruba          ABW   2321.21   2438.55
1             Andorra          AND    524.38    491.38
2         Afghanistan          AFG    781.07  12251.45
3              Angola          AGO   9541.53  29710.03
4             Albania          ALB   3021.61   4668.09
..                ...          ...       ...       ...
243       Yemen, Rep.          YEM  14638.66  22295.36
244      South Africa          ZAF 368610.51 477241.72
245  Congo, Dem. Rep.          COD   1646.48   3424.98
246            Zambia          ZMB   1822.50   3047.28
247          Zimbabwe          ZWE  13886.93   9860.56

[212 rows x 4 columns]

In [286]:
# Converting units from kilotones to megatones for better readability.

df= df[['Country Name', '2000', '2011']]
df['Country']= df['Country Name']
df['2000_Mt']= df['2000']/1000
df['2011_Mt']= df['2011']/1000

df= df[['Country', '2000_Mt', '2011_Mt']]
df

              Country  2000_Mt  2011_Mt
0               Aruba     2.32     2.44
1             Andorra     0.52     0.49
2         Afghanistan     0.78    12.25
3              Angola     9.54    29.71
4             Albania     3.02     4.67
..                ...      ...      ...
243       Yemen, Rep.    14.64    22.30
244      South Africa   368.61   477.24
245  Congo, Dem. Rep.     1.65     3.42
246            Zambia     1.82     3.05
247          Zimbabwe    13.89     9.86

[212 rows x 3 columns]

In [287]:
# Dropping rows with null values and reseting the indexes of the data,
# in order to avoid further confusion in the calculation process.

df.isnull().sum()
df= df.dropna()

df.reset_index(drop= True, inplace= True)
df

              Country  2000_Mt  2011_Mt
0               Aruba     2.32     2.44
1             Andorra     0.52     0.49
2         Afghanistan     0.78    12.25
3              Angola     9.54    29.71
4             Albania     3.02     4.67
..                ...      ...      ...
189       Yemen, Rep.    14.64    22.30
190      South Africa   368.61   477.24
191  Congo, Dem. Rep.     1.65     3.42
192            Zambia     1.82     3.05
193          Zimbabwe    13.89     9.86

[194 rows x 3 columns]

In [288]:
import numpy as np

# 1. Permanently KEEP only rows where '2000_Mt' is greater than 40

df = df[df['2000_Mt'] > 40]
df

                  Country  2000_Mt  2011_Mt
5    United Arab Emirates   112.56   178.48
6               Argentina   141.08   190.03
9               Australia   329.48   369.04
10                Austria    62.19    65.20
13                Belgium   114.89    97.77
..                    ...      ...      ...
181         United States  5701.83  5305.57
182            Uzbekistan   121.06   114.86
184         Venezuela, RB   152.42   188.82
185               Vietnam    53.64   173.21
190          South Africa   368.61   477.24

[59 rows x 3 columns]

In [289]:
# Calculating percentage growth and looking for the fastest growing emitters (2000-2011).

df['Growth %']= (((df['2011_Mt']- df['2000_Mt'])/df['2000_Mt'])*100)

df= df.sort_values(by= 'Growth %', ascending= False).head(15)
df= df.reset_index(drop= True)
df.index= df.index+1
df= df.style.set_caption("Fastest Growing Emitters (2000-2011)")
df

In [290]:
# Calculating top 10 countries with emission reductions (2000-2011).

pd.set_option('display.max_columns', 8)
pd.set_option('display.max_row', 20)

clean_df = dataf.copy()
clean_df = dataf.drop(columns=["Indicator Code", "Indicator Name"])


# Keep only valid country codes
clean_df = clean_df[clean_df["Country Code"].isin(valid_codes)]



""" # We'll drop na after selecting the necessary columns. To avoid miscalculations.
# Drop missing values
clean_df = clean_df.dropna()
"""

" # We'll drop na after selecting the necessary columns. To avoid miscalculations.\n# Drop missing values\nclean_df = clean_df.dropna()\n"

In [291]:
#Importing viewing the previously saved data.

clean_df.to_csv(r"C:\Users\dell\Desktop\data\clean_co2.csv", index=False)

clean_df = pd.read_csv(r"C:\Users\dell\Desktop\data\clean_co2.csv")
clean_df

,Country Name,Country Code,1960,1961,...,2008,2009,2010,2011
0,Aruba,ABW,NaN,NaN,...,2508.23,2522.90,2456.89,2438.55
1,Andorra,AND,NaN,NaN,...,539.05,517.05,517.05,491.38
2,Afghanistan,AFG,414.37,491.38,...,4217.05,6776.62,8470.77,12251.45
3,Angola,AGO,550.05,454.71,...,27172.47,29361.67,29743.04,29710.03
4,Albania,ALB,2024.18,2280.87,...,4657.09,4488.41,4415.07,4668.09
...,...,...,...,...,...,...,...,...,...
207,"Yemen, Rep.",YEM,3634.00,2665.91,...,22097.34,23556.81,25716.67,22295.36
208,South Africa,ZAF,97934.57,102213.96,...,469089.97,477806.43,454950.02,477241.72
209,"Congo, Dem. Rep.",COD,2321.21,2357.88,...,2992.27,2911.60,3252.63,3424.98
210,Zambia,ZMB,NaN,NaN,...,2159.86,2486.23,2673.24,3047.28
211,Zimbabwe,ZWE,NaN,NaN,...,7682.36,8239.75,9028.15,9860.56

In [292]:
# Preparing the data for Calculating the Top 10 countries with emission reductions (2000-2011)

reddf= clean_df[['Country Name', '2000', '2011']]
reddf["2000"]= reddf["2000"]/1000
reddf["2011"]= reddf["2011"]/1000

# Renaming columns for better readibility.
reddf= reddf.rename(columns= {
    "Country Name":"Country",
    "2000":"2000_Mt",
    "2011":"2011_Mt"
})
reddf

              Country  2000_Mt  2011_Mt
0               Aruba     2.32     2.44
1             Andorra     0.52     0.49
2         Afghanistan     0.78    12.25
3              Angola     9.54    29.71
4             Albania     3.02     4.67
..                ...      ...      ...
207       Yemen, Rep.    14.64    22.30
208      South Africa   368.61   477.24
209  Congo, Dem. Rep.     1.65     3.42
210            Zambia     1.82     3.05
211          Zimbabwe    13.89     9.86

[212 rows x 3 columns]

In [293]:

# import sys
# !{sys.executable} -m pip install jinja2


# Add columns
reddf["Absolute Decrease"] = reddf["2000_Mt"] - reddf["2011_Mt"]
reddf["% Decrease"] = ((reddf["2000_Mt"] - reddf["2011_Mt"]) / reddf["2000_Mt"]) * 100

# Sort and keep top 10
reddf = reddf.sort_values(by="Absolute Decrease", ascending=False).head(10)

# Reset index starting from 1
reddf.reset_index(drop=True, inplace=True)
reddf.index = reddf.index + 1

# Drop missing values
reddf = reddf.dropna()

# Style table
reddf.style.set_caption("Top 10 Countries with Highest Emission Reductions (2000-2011)")

In [294]:
import pandas as pd


code_to_region = {
    'NAC': 'North America',
    'SAS': 'South Asia',
    'EAP': 'East Asia & Pacific',
    'ECA': 'Europe & Central Asia',
    'LAC': 'Latin America & Caribbean',
    'MNA': 'Middle East & North Africa',
    'SSA': 'Sub-Saharan Africa'
}

# Filter raw data to official aggregate codes only.
filtered = rawdf[rawdf['Country Code'].isin(code_to_region.keys())].copy()

# Map codes to region names
filtered['Region'] = filtered['Country Code'].map(code_to_region)

# Convert kt → Mt
filtered['2011 (Mt)'] = filtered['2011'] / 1000
filtered['2000 (Mt)'] = filtered['2000'] / 1000


# Group by region and sum
agg_df = filtered.groupby('Region', as_index=False).agg({
    '2000 (Mt)': 'sum',
    '2011 (Mt)': 'sum'
})
agg_df

                       Region  2000 (Mt)  2011 (Mt)
0         East Asia & Pacific    4213.07   10486.42
1       Europe & Central Asia    1128.01    1400.69
2   Latin America & Caribbean     932.04    1210.41
3  Middle East & North Africa     872.98    1309.43
4               North America    6236.81    5791.43
5                  South Asia    1336.13    2328.35
6          Sub-Saharan Africa     550.44     738.90

In [295]:
# Calculate % growth since 2000

agg_df['% Growth Since 2000'] = ((agg_df['2011 (Mt)'] - agg_df['2000 (Mt)']) / agg_df['2000 (Mt)']) * 100

# Keep Excel-like order
regions_order = [
    "East Asia & Pacific",
    "Europe & Central Asia",
    "North America",
    "Middle East & North Africa",
    "South Asia",
    "Latin America & Caribbean",
    "Sub-Saharan Africa"
]
agg_df['Region'] = pd.Categorical(agg_df['Region'], categories=regions_order)
agg_df = agg_df.sort_values(by= '% Growth Since 2000', ascending= False)

# Keep only the three necessary columns
agg_df = agg_df[['Region', '2011 (Mt)', '% Growth Since 2000']]
agg_df

                       Region  2011 (Mt)  % Growth Since 2000
0         East Asia & Pacific   10486.42               148.90
5                  South Asia    2328.35                74.26
3  Middle East & North Africa    1309.43                50.00
6          Sub-Saharan Africa     738.90                34.24
2   Latin America & Caribbean    1210.41                29.87
1       Europe & Central Asia    1400.69                24.17
4               North America    5791.43                -7.14

In [296]:
# Reset index starting from 1
agg_df = agg_df.reset_index(drop=True)
agg_df.index = agg_df.index + 1

# Add caption for display
agg_df = agg_df.style.set_caption("Regional Emissions in 2011")
agg_df

In [297]:
# China vs United States Emissions Comparisons
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 50)

uschdf= dataf[['Country Name', 'Country Code', '2000', '2011']]
uschdf

         Country Name Country Code      2000      2011
0               Aruba          ABW   2321.21   2438.55
1             Andorra          AND    524.38    491.38
2         Afghanistan          AFG    781.07  12251.45
3              Angola          AGO   9541.53  29710.03
4             Albania          ALB   3021.61   4668.09
..                ...          ...       ...       ...
243       Yemen, Rep.          YEM  14638.66  22295.36
244      South Africa          ZAF 368610.51 477241.72
245  Congo, Dem. Rep.          COD   1646.48   3424.98
246            Zambia          ZMB   1822.50   3047.28
247          Zimbabwe          ZWE  13886.93   9860.56

[248 rows x 4 columns]

In [299]:
# Data cleaning for US China comparisons.

uschdf= uschdf.isnull().sum()
uschdf

Country Name     0
Country Code     0
2000            21
2011            16
dtype: int64